os: linux
dist: xenial
language: node_js
node_js: 10

before_install: npm i -g npm@latest

install: travis_retry npm install

script: npm run test

after_success: npm run report-coverage

deploy:
  provider: script
  script: ./deployment/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    # tags: true
